sample=$1
resolution=$2

cooler balance --cis-only --ignore-diags 2 -p 8 /mnt/f/toxo_project/HiC/Hsapien_output/output_files/${sample}_HiC/hicexplorer_files_two_reps/${resolution}/${sample}_${resolution}.cool
cooler dump --header -t bins /mnt/f/toxo_project/HiC/Hsapien_output/output_files/${sample}_HiC/hicexplorer_files_two_reps/${resolution}/${sample}_${resolution}.cool | cut -f1-3 > /mnt/f/toxo_project/HiC/Hsapien_output/output_files/${sample}_HiC/hicexplorer_files_two_reps/${sample}_bins_${resolution}.tsv
cooltools genome gc /mnt/f/toxo_project/HiC/Hsapien_output/output_files/${sample}_HiC/hicexplorer_files_two_reps/${sample}_bins_${resolution}.tsv /mnt/f/organism_genome/Hsapien_autosomes/GRCh38.fasta > /mnt/f/toxo_project/HiC/Hsapien_output/output_files/${sample}_HiC/hicexplorer_files_two_reps/${sample}_gc_${resolution}.tsv
cooltools eigs-cis -o /mnt/f/toxo_project/HiC/Hsapien_output/output_files/${sample}_HiC/hicexplorer_files_two_reps/${sample}_${resolution} --phasing-track /mnt/f/toxo_project/HiC/Hsapien_output/output_files/${sample}_HiC/hicexplorer_files_two_reps/${sample}_gc_${resolution}.tsv --n-eigs 1 /mnt/f/toxo_project/HiC/Hsapien_output/output_files/${sample}_HiC/hicexplorer_files_two_reps/${resolution}/${sample}_${resolution}.cool
cooltools expected-cis /mnt/f/toxo_project/HiC/Hsapien_output/output_files/${sample}_HiC/hicexplorer_files_two_reps/${resolution}/${sample}_${resolution}.cool --nproc 8 -o /mnt/f/toxo_project/HiC/Hsapien_output/output_files/${sample}_HiC/hicexplorer_files_two_reps/${sample}_${resolution}_expected.tsv
cooltools saddle -t cis --qrange 0.02 0.98 -o /mnt/f/toxo_project/HiC/Hsapien_output/output_files/${sample}_HiC/hicexplorer_files_two_reps/${sample}_${resolution}_saddle /mnt/f/toxo_project/HiC/Hsapien_output/output_files/${sample}_HiC/hicexplorer_files_two_reps/${resolution}/${sample}_${resolution}.cool /mnt/f/toxo_project/HiC/Hsapien_output/output_files/${sample}_HiC/hicexplorer_files_two_reps/${sample}_${resolution}.cis.vecs.tsv /mnt/f/toxo_project/HiC/Hsapien_output/output_files/${sample}_HiC/hicexplorer_files_two_reps/${sample}_${resolution}_expected.tsv
python3 /mnt/f/scripts/hic_scripts/plot_saddle.py /mnt/f/toxo_project/HiC/Hsapien_output/output_files/${sample}_HiC/hicexplorer_files_two_reps/${sample}_${resolution}_saddle.saddledump.npz
